In [1]:
import nltk
import tensorflow as tf
import json
import numpy as np
import pandas as pd
import pickle
import random

In [2]:
# Open and Load the Dataset File
file = open('./intents.json')
dataset = json.load(file)

In [3]:
words = []
documents = []
tags = []

for data in dataset["intents"]:
    for pattern in data['patterns']:
        # Tokenize each word using nltk library
        # Tokenize -> Break the Sentence into words
        word = nltk.word_tokenize(pattern)
        # print(word)
        words.extend(word)
        # Group the Tokenized Word and the Tag
        documents.append((word, data['tag']))
        # Add Tags from the dataset
        if data['tag'] not in tags:
            tags.append(data['tag'])

In [4]:
documents

[(['Hi', 'there'], 'greeting'),
 (['How', 'are', 'you'], 'greeting'),
 (['Is', 'anyone', 'there', '?'], 'greeting'),
 (['Hey'], 'greeting'),
 (['Hola'], 'greeting'),
 (['Hello'], 'greeting'),
 (['Good', 'day'], 'greeting'),
 (['Bye'], 'goodbye'),
 (['See', 'you', 'later'], 'goodbye'),
 (['Goodbye'], 'goodbye'),
 (['Nice', 'chatting', 'to', 'you', ',', 'bye'], 'goodbye'),
 (['Till', 'next', 'time'], 'goodbye'),
 (['Thanks'], 'thanks'),
 (['Thank', 'you'], 'thanks'),
 (['That', "'s", 'helpful'], 'thanks'),
 (['Awesome', ',', 'thanks'], 'thanks'),
 (['Thanks', 'for', 'helping', 'me'], 'thanks'),
 (['How', 'you', 'could', 'help', 'me', '?'], 'options'),
 (['What', 'you', 'can', 'do', '?'], 'options'),
 (['What', 'help', 'you', 'provide', '?'], 'options'),
 (['How', 'you', 'can', 'be', 'helpful', '?'], 'options'),
 (['What', 'support', 'is', 'offered'], 'options'),
 (['How', 'to', 'check', 'Adverse', 'drug', 'reaction', '?'], 'adverse_drug'),
 (['Open', 'adverse', 'drugs', 'module'], 'adver

In [5]:
tags

['greeting',
 'goodbye',
 'thanks',
 'options',
 'adverse_drug',
 'blood_pressure',
 'blood_pressure_search',
 'pharmacy_search',
 'hospital_search']

In [20]:
words

["'s",
 ',',
 '?',
 'a',
 'adverse',
 'all',
 'anyone',
 'are',
 'awesome',
 'be',
 'behavior',
 'blood',
 'by',
 'bye',
 'can',
 'causing',
 'chatting',
 'check',
 'could',
 'data',
 'day',
 'detail',
 'do',
 'dont',
 'drug',
 'entry',
 'find',
 'for',
 'give',
 'good',
 'goodbye',
 'have',
 'hello',
 'help',
 'helpful',
 'helping',
 'hey',
 'hi',
 'history',
 'hola',
 'hospital',
 'how',
 'i',
 'id',
 'is',
 'later',
 'list',
 'load',
 'locate',
 'log',
 'looking',
 'lookup',
 'management',
 'me',
 'module',
 'nearby',
 'next',
 'nice',
 'of',
 'offered',
 'open',
 'patient',
 'pharmacy',
 'pressure',
 'provide',
 'reaction',
 'related',
 'result',
 'search',
 'searching',
 'see',
 'show',
 'suitable',
 'support',
 'task',
 'thank',
 'thanks',
 'that',
 'there',
 'till',
 'time',
 'to',
 'transfer',
 'up',
 'want',
 'what',
 'which',
 'with',
 'you']

In [6]:
# Lemmatize the data
# Lemmatize -> Grouping the differents words into one word 
# (eg. Playing -> Play, Plays -> Play)
lemmatizer = nltk.stem.WordNetLemmatizer()
# Lemmatize the unique word in the words 
words = [lemmatizer.lemmatize(word.lower()) for word in words]
words = sorted(list(set(words)))

In [7]:
pickle.dump(words, open('words.pkl', 'wb'))
pickle.dump(tags, open('tags.pkl', 'wb'))

In [8]:
# Training Data 

training = []

for docs in documents:
    bag_of_words = np.zeros(shape=(len(words)), dtype=np.float32)
    tag_pattern = np.zeros(shape=(len(tags)), dtype=np.float32)

    # Get the word in each pattern
    words_pattern = docs[0]
    # Lemmatize the word in each pattern
    words_pattern = [lemmatizer.lemmatize(word.lower()) for word in words_pattern]

    # Get the tag in each pattern
    tag = docs[1]

    # create the bag of words array with 1, if word is found in current pattern
    for word in words_pattern:
        if word in words:
            bag_of_words[words.index(word)] = 1
        else : 
            bag_of_words[words.index(word)] = 0

    # output is a '0' for each tag and '1' for current tag (for each pattern)
    tag_pattern[tags.index(tag)] = 1

    training.append([bag_of_words, tag_pattern])

    

In [9]:
#Shuffle the training data (features)
random.shuffle(training)
training = np.array(training, dtype='object')

In [10]:
training[:, 0][:3]

array([array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0.], dtype=float32)                                    ,
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
              0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
              0., 0., 0., 1.], dtype=float32)                                    ,
       array([

In [11]:
list(training[:, 0][:3])

[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
      

In [12]:
# create a new dimension for the x_train and y_train
x_train = np.array(list(training[:,0]))
y_train = np.array(list(training[:,1]))

In [13]:
# Convert to Tensor
x_train = tf.convert_to_tensor(x_train)
y_train = tf.convert_to_tensor(y_train)

In [14]:
x_train, y_train

(<tf.Tensor: shape=(47, 89), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(47, 9), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.,

In [15]:
# Build model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, input_shape=(len(x_train[0]),), activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(64 , activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(y_train[0]) , activation='softmax'),
])

In [16]:
model.compile(
    loss=tf.keras.losses.categorical_crossentropy,
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, decay=1e-6, momentum=0.9, nesterov=True),
    metrics=['accuracy']
)

In [17]:
hist = model.fit(
    x_train, y_train,
    epochs=200,
    batch_size=5, 
    verbose=1,
    # callbacks=[
    #     tf.keras.callbacks.ModelCheckpoint(
    #         './Chatbot_Model',
    #         save_freq='epoch',
    #         save_best_only=True,

    #     )
    # ]
)

Epoch 1/200
10/10 [==============================] - 1s 9ms/step - loss: 2.2624 - accuracy: 0.1064
Epoch 2/200
10/10 [==============================] - 0s 7ms/step - loss: 2.1705 - accuracy: 0.1277
Epoch 3/200
10/10 [==============================] - 0s 6ms/step - loss: 2.1120 - accuracy: 0.2553
Epoch 4/200
10/10 [==============================] - 0s 7ms/step - loss: 2.0246 - accuracy: 0.2340
Epoch 5/200
10/10 [==============================] - 0s 6ms/step - loss: 1.9280 - accuracy: 0.2766
Epoch 6/200
10/10 [==============================] - 0s 6ms/step - loss: 1.9090 - accuracy: 0.2979
Epoch 7/200
10/10 [==============================] - 0s 6ms/step - loss: 1.7117 - accuracy: 0.4043
Epoch 8/200
10/10 [==============================] - 0s 6ms/step - loss: 1.5203 - accuracy: 0.5106
Epoch 9/200
10/10 [==============================] - 0s 6ms/step - loss: 1.3852 - accuracy: 0.5957
Epoch 10/200
10/10 [==============================] - 0s 6ms/step - loss: 1.3386 - accuracy: 0.6596
Epoch 11/

In [18]:
model.save('Chatbot.h5', hist)

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               11520     
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dense_2 (Dense)             (None, 9)                 585       
                                                                 
Total params: 20,361
Trainable params: 20,361
Non-trainable params: 0
_________________________________________________________________


In [19]:
file.close()